version: "3.7"
services:
  web1:
    build: ./quote_gen
#    container_name: quote-gen-container
    ports:
      - "5000-5001:5000"
    deploy:
      mode: replicated
      replicas: 2

  web2:
    build: ./quote_disp
#    container_name: quote-disp-container
    ports:
      - "5002-5003:5001"
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - web1